### ISSUE TITLE
Trash collection on Thursday nights?

### ISSUE THREAD

**Issue by marykatefain** [Uptwinkles/manual#1]
Any particular reason you have people collecting the trash on Thursdays instead of Sundays?

**Comment by alexgleason** [comment]
**Background:** The trash level within the house is unaffected by the trash level of the garage cans as long as the garage cans don't overflow. So as long as the trash in the house is emptied once weekly, the day of the week this happens on doesn't affect the trash levels in the house at any given time.

**Purpose:** Splitting this chore among two separate days will allow us to fall back on completing the task on another day if it wasn't completed on Thursday. Basically if the trash person forgets on Thursday, they still have Friday, Saturday, and Sunday to redeem themselves. If they forget on Sunday, the trash will overflow.

**Comment by marykatefain** [comment]
It just seems unnecessarily tedious to have to move trash twice in the week instead of once. Why not just roll the trash cans out while you are filling them up? Also TBH people should be responsible for bringing their own room trash down. We agreed we weren't babysitting rooms, and bathrooms are the domain of the people who use them. The trash collector should just go around to the public spaces Sunday night on their way to roll the trash out IMO. I don't think all this fallback is necessary when we are working on an accountability system anyways.

**Comment by alexgleason** [comment]
We're following Twink now
